version: "3"
services:

  zabbix-pgsql:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      PG_DATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /opt/postgres:/var/lib/postgresql/data/pgdata

  zabbix-srv:
    image: zabbix/zabbix-server-pgsql:7.0.0-alpine
    restart: always
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_HISTORYSTORAGETYPES: log,text
      ZBX_DEBUGLEVEL: 1
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_MAXHOUSEKEEPERDELETE: 5000
    depends_on:
      - zabbix-pgsql
    volumes:
      - /usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:7.0.0-alpine
    restart: always
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
      ZBX_POSTMAXSIZE: 64M
      PHP_TZ: "Europe/Moscow"
      ZBX_MAXEXECUTIONTIME: 500
    depends_on:
      - zabbix-pgsql
      - zabbix-srv
    ports:
      - 80:80

  zabbix-agent:
    image: zabbix/zabbix-agent:7.0.0-alpine
    privileged: true
    network_mode: "host"
    restart: unless-stopped
    environment:
      - ZBX_SERVER_HOST=127.0.0.1

  adminer:  #Optional for accessing databases
    image: adminer
    restart: always
    ports:
      - 8080:8080

  zabbix-grafana:
    image: grafana/grafana:11.1.1
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel
    ports:
      - 3000:3000
    volumes:
      - /opt/grafana:/var/lib/grafana
