version: "3"
services:

  postgres-server:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      PG_DATA: /var/lib/postgresql/data/pgdata #data storage

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:ubuntu-latest
    restart: always
    environment:   # The Postgres database value variable
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_HISTORYSTORAGETYPES: log,text #Zabbix configuration variables
      ZBX_DEBUGLEVEL: 1
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_MAXHOUSEKEEPERDELETE: 5000
    depends_on:
      - postgres-server
    volumes:
      - /usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-latest
    restart: always
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
      ZBX_POSTMAXSIZE: 64M
      PHP_TZ: "Europe/Moscow"
      ZBX_MAXEXECUTIONTIME: 500
    depends_on:
      - postgres-server
      - zabbix-server
    ports:
      - 80:80

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    privileged: true
    network_mode: "host"
    restart: unless-stopped
    environment:
      - ZBX_SERVER_HOST=127.0.0.1

  adminer:  #Optional for accessing databases
    image: adminer
    restart: always
    ports:
      - 8080:8080

  grafana-xxl:  #optional more functional and creative UI
    image: monitoringartist/grafana-xxl:latest
    ports:
     - 3000:3000
